cmake_minimum_required(VERSION 3.16)

project(LearningAlgorithm)

add_subdirectory(BinaryAlgorithm)
add_subdirectory(CombinationSum)
add_subdirectory(Maths)
add_subdirectory(Parser)
add_subdirectory(Pattern)
add_subdirectory(Compression)
add_subdirectory(KMax)
add_subdirectory(MinSlidingWindow)
add_subdirectory(RateLimiter)
add_subdirectory(RegularExpressionDynamic)
add_subdirectory(SortingAlgorithm)
add_subdirectory(SplitOrderedMap)
add_subdirectory(StringAlgorithm)
add_subdirectory(TicTacToe)
add_subdirectory(WildcardSearch)

