cmake_minimum_required(VERSION 3.16)

project(LearningAlgorithm)

add_subdirectory(Backtracking)
add_subdirectory(LinkedList)
add_subdirectory(BinaryAlgorithm)
add_subdirectory(Maths)
add_subdirectory(Parser)
add_subdirectory(Pattern)
add_subdirectory(Compression)
add_subdirectory(Dynamic)
add_subdirectory(SortingAlgorithm)
add_subdirectory(StringAlgorithm)


